[package]
name = "fuzzer_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
lazy_static = "1.5.0"
libc = "0.2.172"
memmap2 = "0.9.5"
bincode = "1.3"
coverage_runtime = { path = "../coverage_runtime" }

[lib]
crate-type = ["rlib", "cdylib"]
