[package]
name = "race_runtime"
version = "0.1.0"
edition = "2021"

[dependencies]
libc = "0.2.174"
instrument = { path = "../instrument" }
lazy_static = "1.5.0"
colored = "3.0.0"

[lib]
crate-type = ["rlib", "cdylib"]
