[package]
name = "tools"
version = "0.1.0"
edition = "2021"

[dependencies]
instrument = { path = "../instrument" }
inkwell = { version = "0.5.0", features = ["llvm17-0"] }
anyhow = "1.0.97"
clap = "4.5.34"

[dev-dependencies]
defer-lite = "1.0.0"
goldentests = "1.2.0"
